# Generated by Django 3.2.7 on 2021-09-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Iime', 'Full Iime'), ('Part Iime', 'Part Iime')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
